const char calc_dd_coeff_ocl[] ={
"\n"
"#pragma OPENCL EXTENSION cl_khr_fp64 : enable\n"
"\n"
"kernel void calc_dd_coeff(\n"
"    const double dx,\n"
"    const double dy,\n"
"    const double dz,\n"
"    global const double * restrict eta,\n"
"    global const double * restrict xi,\n"
"    global double * restrict dd_i,\n"
"    global double * restrict dd_j,\n"
"    global double * restrict dd_k\n"
"    )\n"
"{\n"
"    size_t a = get_global_id(0);\n"
"\n"
"    // There is only one dd_i so just get the first work-item to do this\n"
"    if (a == 0 && get_group_id(0) == 0)\n"
"        dd_i[0] = 2.0 / dx;\n"
"\n"
"    dd_j[a] = (2.0 / dy) * eta[a];\n"
"    dd_k[a] = (2.0 / dz) * xi[a];\n"
"}\n"
};
