const char outer_source_ocl[] ={
"\n"
"#pragma OPENCL EXTENSION cl_khr_fp64 : enable\n"
"\n"
"\n"
"#define SOURCE_INDEX(m,g,i,j,k,cmom,ng,nx,ny) ((m)+((cmom)*(g))+((cmom)*(ng)*(i))+((cmom)*(ng)*(nx)*(j))+((cmom)*(ng)*(nx)*(ny)*(k)))\n"
"#define FIXED_SOURCE_INDEX(g,i,j,k,ng,nx,ny) ((g)+((ng)*(i))+((ng)*(nx)*(j))+((ng)*(nx)*(ny)*(k)))\n"
"#define SCATTERING_MATRIX_INDEX(m,g1,g2,nmom,ng) ((m)+((nmom)*(g1))+((nmom)*(ng)*(g2)))\n"
"#define SCALAR_FLUX_INDEX(g,i,j,k,ng,nx,ny) ((g)+((ng)*(i))+((ng)*(nx)*(j))+((ng)*(nx)*(ny)*(k)))\n"
"#define SCALAR_FLUX_MOMENTS_INDEX(m,g,i,j,k,cmom,ng,nx,ny) ((m)+((cmom-1)*(g))+((cmom-1)*(ng)*(i))+((cmom-1)*(ng)*(nx)*(j))+((cmom-1)*(ng)*(nx)*(ny)*(k)))\n"
"\n"
"\n"
"#define outer_source(m,g,i,j,k) outer_source[SOURCE_INDEX((m),(g),(i),(j),(k),cmom,ng,nx,ny)]\n"
"#define fixed_source(g,i,j,k) fixed_source[FIXED_SOURCE_INDEX((g),(i),(j),(k),ng,nx,ny)]\n"
"#define scattering_matrix(m,g1,g2) scattering_matrix[SCATTERING_MATRIX_INDEX((m),(g1),(g2),nmom,ng)]\n"
"#define scalar_flux(g,i,j,k) scalar_flux[SCALAR_FLUX_INDEX((g),(i),(j),(k),ng,nx,ny)]\n"
"#define scalar_flux_moments(m,g,i,j,k) scalar_flux_moments[SCALAR_FLUX_MOMENTS_INDEX((m),(g),(i),(j),(k),cmom,ng,nx,ny)]\n"
"\n"
"// 3D kernel, in local nx,ny,nz dimensions\n"
"// Probably not going to vectorise very well..\n"
"kernel void calc_outer_source(\n"
"    const unsigned int nx,\n"
"    const unsigned int ny,\n"
"    const unsigned int nz,\n"
"    const unsigned int ng,\n"
"    const unsigned int cmom,\n"
"    const unsigned int nmom,\n"
"    global const double * restrict fixed_source,\n"
"    global const double * restrict scattering_matrix,\n"
"    global const double * restrict scalar_flux,\n"
"    global const double * restrict scalar_flux_moments,\n"
"    global double * restrict outer_source\n"
"    )\n"
"{\n"
"    const size_t i = get_global_id(0);\n"
"    const size_t j = get_global_id(1);\n"
"    const size_t k = get_global_id(2);\n"
"\n"
"    for (unsigned int g = 0; g < ng; g++)\n"
"    {\n"
"        // Set first moment to the fixed source\n"
"        outer_source(0,g,i,j,k) = fixed_source(g,i,j,k);\n"
"\n"
"        // Loop over groups and moments to compute out-of-group scattering\n"
"        for (unsigned int g2 = 0; g2 < ng; g2++)\n"
"        {\n"
"            if (g == g2)\n"
"                continue;\n"
"            // Compute scattering source\n"
"            outer_source(0,g,i,j,k) += scattering_matrix(0,g2,g) * scalar_flux(g2,i,j,k);\n"
"            // Other moments\n"
"            unsigned int mom = 1;\n"
"            for (unsigned int l = 1; l < nmom; l++)\n"
"            {\n"
"                for (unsigned int m = 0; m < 2*l+1; m++)\n"
"                {\n"
"                    outer_source(mom,g,i,j,k) += scattering_matrix(l,g2,g) * scalar_flux_moments(mom-1,g2,i,j,k);\n"
"                    mom += 1;\n"
"                }\n"
"            }\n"
"        }\n"
"    }\n"
"\n"
"}\n"
};
